# The following is automatically generated by code_factory.py

from numpy import int64
from numba import njit


from mcdc.code_factory.array_return import array_return, array_result


import numba as nb


@njit
def region_RPN_tokens(index, cell, data):
    offset = cell["region_RPN_tokens_offset"]
    return int64(data[offset + index])


@array_return(nb.types.float64)
def region_RPN_tokens_all(cell, data):
    start = cell["region_RPN_tokens_offset"]
    size = cell["region_RPN_tokens_length"]
    end = start + size
    return array_result(data[start:end])


@njit
def region_RPN_tokens_last(cell, data):
    start = cell["region_RPN_tokens_offset"]
    size = cell["region_RPN_tokens_length"]
    end = start + size
    return int64(data[end - 1])


@array_return(nb.types.float64)
def region_RPN_tokens_chunk(start, length, cell, data):
    start += cell["region_RPN_tokens_offset"]
    end = start + length
    return array_result(data[start:end])


@njit
def surface_IDs(index, cell, data):
    offset = cell["surface_IDs_offset"]
    return int64(data[offset + index])


@array_return(nb.types.float64)
def surface_IDs_all(cell, data):
    start = cell["surface_IDs_offset"]
    size = cell["N_surface"]
    end = start + size
    return array_result(data[start:end])


@njit
def surface_IDs_last(cell, data):
    start = cell["surface_IDs_offset"]
    size = cell["N_surface"]
    end = start + size
    return int64(data[end - 1])


@array_return(nb.types.float64)
def surface_IDs_chunk(start, length, cell, data):
    start += cell["surface_IDs_offset"]
    end = start + length
    return array_result(data[start:end])


@njit
def collision_tally_IDs(index, cell, data):
    offset = cell["collision_tally_IDs_offset"]
    return int64(data[offset + index])


@array_return(nb.types.float64)
def collision_tally_IDs_all(cell, data):
    start = cell["collision_tally_IDs_offset"]
    size = cell["N_collision_tally"]
    end = start + size
    return array_result(data[start:end])


@njit
def collision_tally_IDs_last(cell, data):
    start = cell["collision_tally_IDs_offset"]
    size = cell["N_collision_tally"]
    end = start + size
    return int64(data[end - 1])


@array_return(nb.types.float64)
def collision_tally_IDs_chunk(start, length, cell, data):
    start += cell["collision_tally_IDs_offset"]
    end = start + length
    return array_result(data[start:end])


@njit
def tracklength_tally_IDs(index, cell, data):
    offset = cell["tracklength_tally_IDs_offset"]
    return int64(data[offset + index])


@array_return(nb.types.float64)
def tracklength_tally_IDs_all(cell, data):
    start = cell["tracklength_tally_IDs_offset"]
    size = cell["N_tracklength_tally"]
    end = start + size
    return array_result(data[start:end])


@njit
def tracklength_tally_IDs_last(cell, data):
    start = cell["tracklength_tally_IDs_offset"]
    size = cell["N_tracklength_tally"]
    end = start + size
    return int64(data[end - 1])


@array_return(nb.types.float64)
def tracklength_tally_IDs_chunk(start, length, cell, data):
    start += cell["tracklength_tally_IDs_offset"]
    end = start + length
    return array_result(data[start:end])
