# The following is automatically generated by code_factory.py

from numpy import int64
from numba import njit


from mcdc.code_factory.array_return import array_return, array_result


import numba as nb


@njit
def nuclide_IDs(index, material, data):
    offset = material["nuclide_IDs_offset"]
    return int64(data[offset + index])


@array_return(nb.types.float64)
def nuclide_IDs_all(material, data):
    start = material["nuclide_IDs_offset"]
    size = material["N_nuclide"]
    end = start + size
    return array_result(data[start:end])


@njit
def nuclide_IDs_last(material, data):
    start = material["nuclide_IDs_offset"]
    size = material["N_nuclide"]
    end = start + size
    return int64(data[end - 1])


@array_return(nb.types.float64)
def nuclide_IDs_chunk(start, length, material, data):
    start += material["nuclide_IDs_offset"]
    end = start + length
    return array_result(data[start:end])


@njit
def element_IDs(index, material, data):
    offset = material["element_IDs_offset"]
    return int64(data[offset + index])


@array_return(nb.types.float64)
def element_IDs_all(material, data):
    start = material["element_IDs_offset"]
    size = material["N_element"]
    end = start + size
    return array_result(data[start:end])


@njit
def element_IDs_last(material, data):
    start = material["element_IDs_offset"]
    size = material["N_element"]
    end = start + size
    return int64(data[end - 1])


@array_return(nb.types.float64)
def element_IDs_chunk(start, length, material, data):
    start += material["element_IDs_offset"]
    end = start + length
    return array_result(data[start:end])


@njit
def nuclide_densities(index, material, data):
    offset = material["nuclide_densities_offset"]
    return data[offset + index]


@array_return(nb.types.float64)
def nuclide_densities_all(material, data):
    start = material["nuclide_densities_offset"]
    size = material["nuclide_densities_length"]
    end = start + size
    return array_result(data[start:end])


@njit
def nuclide_densities_last(material, data):
    start = material["nuclide_densities_offset"]
    size = material["nuclide_densities_length"]
    end = start + size
    return data[end - 1]


@array_return(nb.types.float64)
def nuclide_densities_chunk(start, length, material, data):
    start += material["nuclide_densities_offset"]
    end = start + length
    return array_result(data[start:end])


@njit
def element_densities(index, material, data):
    offset = material["element_densities_offset"]
    return data[offset + index]


@array_return(nb.types.float64)
def element_densities_all(material, data):
    start = material["element_densities_offset"]
    size = material["element_densities_length"]
    end = start + size
    return array_result(data[start:end])


@njit
def element_densities_last(material, data):
    start = material["element_densities_offset"]
    size = material["element_densities_length"]
    end = start + size
    return data[end - 1]


@array_return(nb.types.float64)
def element_densities_chunk(start, length, material, data):
    start += material["element_densities_offset"]
    end = start + length
    return array_result(data[start:end])
