# The following is automatically generated by code_factory.py

from numba import njit


from mcdc.code_factory.array_return import array_return, array_result


import numba as nb


@njit
def value(index, pmf_distribution, data):
    offset = pmf_distribution["value_offset"]
    return data[offset + index]


@array_return(nb.types.float64)
def value_all(pmf_distribution, data):
    start = pmf_distribution["value_offset"]
    size = pmf_distribution["value_length"]
    end = start + size
    return array_result(data[start:end])


@njit
def value_last(pmf_distribution, data):
    start = pmf_distribution["value_offset"]
    size = pmf_distribution["value_length"]
    end = start + size
    return data[end - 1]


@array_return(nb.types.float64)
def value_chunk(start, length, pmf_distribution, data):
    start += pmf_distribution["value_offset"]
    end = start + length
    return array_result(data[start:end])


@njit
def pmf(index, pmf_distribution, data):
    offset = pmf_distribution["pmf_offset"]
    return data[offset + index]


@array_return(nb.types.float64)
def pmf_all(pmf_distribution, data):
    start = pmf_distribution["pmf_offset"]
    size = pmf_distribution["pmf_length"]
    end = start + size
    return array_result(data[start:end])


@njit
def pmf_last(pmf_distribution, data):
    start = pmf_distribution["pmf_offset"]
    size = pmf_distribution["pmf_length"]
    end = start + size
    return data[end - 1]


@array_return(nb.types.float64)
def pmf_chunk(start, length, pmf_distribution, data):
    start += pmf_distribution["pmf_offset"]
    end = start + length
    return array_result(data[start:end])


@njit
def cmf(index, pmf_distribution, data):
    offset = pmf_distribution["cmf_offset"]
    return data[offset + index]


@array_return(nb.types.float64)
def cmf_all(pmf_distribution, data):
    start = pmf_distribution["cmf_offset"]
    size = pmf_distribution["cmf_length"]
    end = start + size
    return array_result(data[start:end])


@njit
def cmf_last(pmf_distribution, data):
    start = pmf_distribution["cmf_offset"]
    size = pmf_distribution["cmf_length"]
    end = start + size
    return data[end - 1]


@array_return(nb.types.float64)
def cmf_chunk(start, length, pmf_distribution, data):
    start += pmf_distribution["cmf_offset"]
    end = start + length
    return array_result(data[start:end])
