# The following is automatically generated by code_factory.py

from numba import njit


from mcdc.code_factory.array_return import array_return, array_result


import numba as nb


@njit
def coefficients(index, polynomial_data, data):
    offset = polynomial_data["coefficients_offset"]
    return data[offset + index]


@array_return(nb.types.float64)
def coefficients_all(polynomial_data, data):
    start = polynomial_data["coefficients_offset"]
    size = polynomial_data["coefficients_length"]
    end = start + size
    return array_result(data[start:end])


@njit
def coefficients_last(polynomial_data, data):
    start = polynomial_data["coefficients_offset"]
    size = polynomial_data["coefficients_length"]
    end = start + size
    return data[end - 1]


@array_return(nb.types.float64)
def coefficients_chunk(start, length, polynomial_data, data):
    start += polynomial_data["coefficients_offset"]
    end = start + length
    return array_result(data[start:end])
