# The following is automatically generated by code_factory.py

from numba import njit


from mcdc.code_factory.array_return import array_return, array_result


import numba as nb


@array_return(nb.types.float64)
def move_velocities_vector(index_1, source, data):
    offset = source["move_velocities_offset"]
    stride = 3
    start = offset + index_1 * stride
    end = start + stride
    return array_result(data[start:end])


@njit
def move_velocities(index_1, index_2, source, data):
    offset = source["move_velocities_offset"]
    stride = 3
    return data[offset + index_1 * stride + index_2]


@array_return(nb.types.float64)
def move_velocities_chunk(start, length, source, data):
    start += source["move_velocities_offset"]
    end = start + length
    return array_result(data[start:end])


@njit
def move_durations(index, source, data):
    offset = source["move_durations_offset"]
    return data[offset + index]


@array_return(nb.types.float64)
def move_durations_all(source, data):
    start = source["move_durations_offset"]
    size = source["N_move"]
    end = start + size
    return array_result(data[start:end])


@njit
def move_durations_last(source, data):
    start = source["move_durations_offset"]
    size = source["N_move"]
    end = start + size
    return data[end - 1]


@array_return(nb.types.float64)
def move_durations_chunk(start, length, source, data):
    start += source["move_durations_offset"]
    end = start + length
    return array_result(data[start:end])


@njit
def move_time_grid(index, source, data):
    offset = source["move_time_grid_offset"]
    return data[offset + index]


@array_return(nb.types.float64)
def move_time_grid_all(source, data):
    start = source["move_time_grid_offset"]
    size = source["N_move_grid"]
    end = start + size
    return array_result(data[start:end])


@njit
def move_time_grid_last(source, data):
    start = source["move_time_grid_offset"]
    size = source["N_move_grid"]
    end = start + size
    return data[end - 1]


@array_return(nb.types.float64)
def move_time_grid_chunk(start, length, source, data):
    start += source["move_time_grid_offset"]
    end = start + length
    return array_result(data[start:end])


@array_return(nb.types.float64)
def move_translations_vector(index_1, source, data):
    offset = source["move_translations_offset"]
    stride = 3
    start = offset + index_1 * stride
    end = start + stride
    return array_result(data[start:end])


@njit
def move_translations(index_1, index_2, source, data):
    offset = source["move_translations_offset"]
    stride = 3
    return data[offset + index_1 * stride + index_2]


@array_return(nb.types.float64)
def move_translations_chunk(start, length, source, data):
    start += source["move_translations_offset"]
    end = start + length
    return array_result(data[start:end])
