# The following is automatically generated by code_factory.py

from numba import njit


from mcdc.code_factory.array_return import array_return, array_result


import numba as nb


@njit
def x(index, structured_mesh, data):
    offset = structured_mesh["x_offset"]
    return data[offset + index]


@array_return(nb.types.float64)
def x_all(structured_mesh, data):
    start = structured_mesh["x_offset"]
    size = structured_mesh["x_length"]
    end = start + size
    return array_result(data[start:end])


@njit
def x_last(structured_mesh, data):
    start = structured_mesh["x_offset"]
    size = structured_mesh["x_length"]
    end = start + size
    return data[end - 1]


@array_return(nb.types.float64)
def x_chunk(start, length, structured_mesh, data):
    start += structured_mesh["x_offset"]
    end = start + length
    return array_result(data[start:end])


@njit
def y(index, structured_mesh, data):
    offset = structured_mesh["y_offset"]
    return data[offset + index]


@array_return(nb.types.float64)
def y_all(structured_mesh, data):
    start = structured_mesh["y_offset"]
    size = structured_mesh["y_length"]
    end = start + size
    return array_result(data[start:end])


@njit
def y_last(structured_mesh, data):
    start = structured_mesh["y_offset"]
    size = structured_mesh["y_length"]
    end = start + size
    return data[end - 1]


@array_return(nb.types.float64)
def y_chunk(start, length, structured_mesh, data):
    start += structured_mesh["y_offset"]
    end = start + length
    return array_result(data[start:end])


@njit
def z(index, structured_mesh, data):
    offset = structured_mesh["z_offset"]
    return data[offset + index]


@array_return(nb.types.float64)
def z_all(structured_mesh, data):
    start = structured_mesh["z_offset"]
    size = structured_mesh["z_length"]
    end = start + size
    return array_result(data[start:end])


@njit
def z_last(structured_mesh, data):
    start = structured_mesh["z_offset"]
    size = structured_mesh["z_length"]
    end = start + size
    return data[end - 1]


@array_return(nb.types.float64)
def z_chunk(start, length, structured_mesh, data):
    start += structured_mesh["z_offset"]
    end = start + length
    return array_result(data[start:end])
