# The following is automatically generated by code_factory.py

from numpy import int64
from numba import njit


from mcdc.code_factory.array_return import array_return, array_result


import numba as nb


@njit
def scores(index, tally, data):
    offset = tally["scores_offset"]
    return int64(data[offset + index])


@array_return(nb.types.float64)
def scores_all(tally, data):
    start = tally["scores_offset"]
    size = tally["scores_length"]
    end = start + size
    return array_result(data[start:end])


@njit
def scores_last(tally, data):
    start = tally["scores_offset"]
    size = tally["scores_length"]
    end = start + size
    return int64(data[end - 1])


@array_return(nb.types.float64)
def scores_chunk(start, length, tally, data):
    start += tally["scores_offset"]
    end = start + length
    return array_result(data[start:end])


@njit
def mu(index, tally, data):
    offset = tally["mu_offset"]
    return data[offset + index]


@array_return(nb.types.float64)
def mu_all(tally, data):
    start = tally["mu_offset"]
    size = tally["mu_length"]
    end = start + size
    return array_result(data[start:end])


@njit
def mu_last(tally, data):
    start = tally["mu_offset"]
    size = tally["mu_length"]
    end = start + size
    return data[end - 1]


@array_return(nb.types.float64)
def mu_chunk(start, length, tally, data):
    start += tally["mu_offset"]
    end = start + length
    return array_result(data[start:end])


@njit
def azi(index, tally, data):
    offset = tally["azi_offset"]
    return data[offset + index]


@array_return(nb.types.float64)
def azi_all(tally, data):
    start = tally["azi_offset"]
    size = tally["azi_length"]
    end = start + size
    return array_result(data[start:end])


@njit
def azi_last(tally, data):
    start = tally["azi_offset"]
    size = tally["azi_length"]
    end = start + size
    return data[end - 1]


@array_return(nb.types.float64)
def azi_chunk(start, length, tally, data):
    start += tally["azi_offset"]
    end = start + length
    return array_result(data[start:end])


@njit
def energy(index, tally, data):
    offset = tally["energy_offset"]
    return data[offset + index]


@array_return(nb.types.float64)
def energy_all(tally, data):
    start = tally["energy_offset"]
    size = tally["energy_length"]
    end = start + size
    return array_result(data[start:end])


@njit
def energy_last(tally, data):
    start = tally["energy_offset"]
    size = tally["energy_length"]
    end = start + size
    return data[end - 1]


@array_return(nb.types.float64)
def energy_chunk(start, length, tally, data):
    start += tally["energy_offset"]
    end = start + length
    return array_result(data[start:end])


@njit
def time(index, tally, data):
    offset = tally["time_offset"]
    return data[offset + index]


@array_return(nb.types.float64)
def time_all(tally, data):
    start = tally["time_offset"]
    size = tally["time_length"]
    end = start + size
    return array_result(data[start:end])


@njit
def time_last(tally, data):
    start = tally["time_offset"]
    size = tally["time_length"]
    end = start + size
    return data[end - 1]


@array_return(nb.types.float64)
def time_chunk(start, length, tally, data):
    start += tally["time_offset"]
    end = start + length
    return array_result(data[start:end])


@njit
def bin(index, tally, data):
    offset = tally["bin_offset"]
    return data[offset + index]


@array_return(nb.types.float64)
def bin_all(tally, data):
    start = tally["bin_offset"]
    size = tally["bin_length"]
    end = start + size
    return array_result(data[start:end])


@njit
def bin_last(tally, data):
    start = tally["bin_offset"]
    size = tally["bin_length"]
    end = start + size
    return data[end - 1]


@array_return(nb.types.float64)
def bin_chunk(start, length, tally, data):
    start += tally["bin_offset"]
    end = start + length
    return array_result(data[start:end])


@njit
def bin_mean(index, tally, data):
    offset = tally["bin_mean_offset"]
    return data[offset + index]


@array_return(nb.types.float64)
def bin_mean_all(tally, data):
    start = tally["bin_mean_offset"]
    size = tally["bin_mean_length"]
    end = start + size
    return array_result(data[start:end])


@njit
def bin_mean_last(tally, data):
    start = tally["bin_mean_offset"]
    size = tally["bin_mean_length"]
    end = start + size
    return data[end - 1]


@array_return(nb.types.float64)
def bin_mean_chunk(start, length, tally, data):
    start += tally["bin_mean_offset"]
    end = start + length
    return array_result(data[start:end])


@njit
def bin_sum_squared_deviations(index, tally, data):
    offset = tally["bin_sum_squared_deviations_offset"]
    return data[offset + index]


@array_return(nb.types.float64)
def bin_sum_squared_deviations_all(tally, data):
    start = tally["bin_sum_squared_deviations_offset"]
    size = tally["bin_sum_squared_deviations_length"]
    end = start + size
    return array_result(data[start:end])


@njit
def bin_sum_squared_deviations_last(tally, data):
    start = tally["bin_sum_squared_deviations_offset"]
    size = tally["bin_sum_squared_deviations_length"]
    end = start + size
    return data[end - 1]


@array_return(nb.types.float64)
def bin_sum_squared_deviations_chunk(start, length, tally, data):
    start += tally["bin_sum_squared_deviations_offset"]
    end = start + length
    return array_result(data[start:end])


@njit
def bin_shape(index, tally, data):
    offset = tally["bin_shape_offset"]
    return int64(data[offset + index])


@array_return(nb.types.float64)
def bin_shape_all(tally, data):
    start = tally["bin_shape_offset"]
    size = tally["bin_shape_length"]
    end = start + size
    return array_result(data[start:end])


@njit
def bin_shape_last(tally, data):
    start = tally["bin_shape_offset"]
    size = tally["bin_shape_length"]
    end = start + size
    return int64(data[end - 1])


@array_return(nb.types.float64)
def bin_shape_chunk(start, length, tally, data):
    start += tally["bin_shape_offset"]
    end = start + length
    return array_result(data[start:end])
