# The following is automatically generated by code_factory.py

from numba import njit


@njit
def region_RPN_tokens(index, cell, data, value):
    offset = cell["region_RPN_tokens_offset"]
    data[offset + index] = value


@njit
def region_RPN_tokens_all(cell, data, value):
    start = cell["region_RPN_tokens_offset"]
    size = cell["region_RPN_tokens_length"]
    end = start + size
    data[start:end] = value


@njit
def region_RPN_tokens_last(cell, data, value):
    start = cell["region_RPN_tokens_offset"]
    size = cell["region_RPN_tokens_length"]
    end = start + size
    data[end - 1] = value


@njit
def region_RPN_tokens_chunk(start, length, cell, data, value):
    start += cell["region_RPN_tokens_offset"]
    end = start + length
    data[start:end] = value


@njit
def surface_IDs(index, cell, data, value):
    offset = cell["surface_IDs_offset"]
    data[offset + index] = value


@njit
def surface_IDs_all(cell, data, value):
    start = cell["surface_IDs_offset"]
    size = cell["N_surface"]
    end = start + size
    data[start:end] = value


@njit
def surface_IDs_last(cell, data, value):
    start = cell["surface_IDs_offset"]
    size = cell["N_surface"]
    end = start + size
    data[end - 1] = value


@njit
def surface_IDs_chunk(start, length, cell, data, value):
    start += cell["surface_IDs_offset"]
    end = start + length
    data[start:end] = value


@njit
def collision_tally_IDs(index, cell, data, value):
    offset = cell["collision_tally_IDs_offset"]
    data[offset + index] = value


@njit
def collision_tally_IDs_all(cell, data, value):
    start = cell["collision_tally_IDs_offset"]
    size = cell["N_collision_tally"]
    end = start + size
    data[start:end] = value


@njit
def collision_tally_IDs_last(cell, data, value):
    start = cell["collision_tally_IDs_offset"]
    size = cell["N_collision_tally"]
    end = start + size
    data[end - 1] = value


@njit
def collision_tally_IDs_chunk(start, length, cell, data, value):
    start += cell["collision_tally_IDs_offset"]
    end = start + length
    data[start:end] = value


@njit
def tracklength_tally_IDs(index, cell, data, value):
    offset = cell["tracklength_tally_IDs_offset"]
    data[offset + index] = value


@njit
def tracklength_tally_IDs_all(cell, data, value):
    start = cell["tracklength_tally_IDs_offset"]
    size = cell["N_tracklength_tally"]
    end = start + size
    data[start:end] = value


@njit
def tracklength_tally_IDs_last(cell, data, value):
    start = cell["tracklength_tally_IDs_offset"]
    size = cell["N_tracklength_tally"]
    end = start + size
    data[end - 1] = value


@njit
def tracklength_tally_IDs_chunk(start, length, cell, data, value):
    start += cell["tracklength_tally_IDs_offset"]
    end = start + length
    data[start:end] = value
