# The following is automatically generated by code_factory.py

from numba import njit


@njit
def grid(index, multi_table_distribution, data, value):
    offset = multi_table_distribution["grid_offset"]
    data[offset + index] = value


@njit
def grid_all(multi_table_distribution, data, value):
    start = multi_table_distribution["grid_offset"]
    size = multi_table_distribution["grid_length"]
    end = start + size
    data[start:end] = value


@njit
def grid_last(multi_table_distribution, data, value):
    start = multi_table_distribution["grid_offset"]
    size = multi_table_distribution["grid_length"]
    end = start + size
    data[end - 1] = value


@njit
def grid_chunk(start, length, multi_table_distribution, data, value):
    start += multi_table_distribution["grid_offset"]
    end = start + length
    data[start:end] = value


@njit
def table_IDs(index, multi_table_distribution, data, value):
    offset = multi_table_distribution["table_IDs_offset"]
    data[offset + index] = value


@njit
def table_IDs_all(multi_table_distribution, data, value):
    start = multi_table_distribution["table_IDs_offset"]
    size = multi_table_distribution["N_table"]
    end = start + size
    data[start:end] = value


@njit
def table_IDs_last(multi_table_distribution, data, value):
    start = multi_table_distribution["table_IDs_offset"]
    size = multi_table_distribution["N_table"]
    end = start + size
    data[end - 1] = value


@njit
def table_IDs_chunk(start, length, multi_table_distribution, data, value):
    start += multi_table_distribution["table_IDs_offset"]
    end = start + length
    data[start:end] = value
